version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carbon_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "7463:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/carbon_dev?schema=public"
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    environment:
      VITE_API_URL: "http://localhost:3000"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
