name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        id: setup_bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: stable
          bun-download-url: https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip
        continue-on-error: true

      - name: "Fallback: install Bun via curl"
        if: steps.setup_bun.outcome != 'success'
        run: |
          curl -fsSL https://bun.sh/install | bash -s -- --no-chmod
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma client
        run: bunx prisma generate

      - name: Lint (if configured)
        run: |
          echo "Skipping workspace lint in CI (configure package scripts to enable)."

      - name: Run tests (if present)
        run: |
          echo "Skipping workspace tests in PR CI (configure package scripts to enable)."

      - name: Build workspaces (optional)
        run: |
          echo "Skipping workspace build in CI (configure package scripts to enable)."

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/mansyar/carbon-mon-rep/backend:${{ github.sha }}
            ghcr.io/mansyar/carbon-mon-rep/backend:latest

      - name: Build and push frontend image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/mansyar/carbon-mon-rep/frontend:${{ github.sha }}
            ghcr.io/mansyar/carbon-mon-rep/frontend:latest
