name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: stable

      - name: Verify Bun
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma client
        run: bunx prisma generate

      - name: Lint (if configured)
        run: bun workspace run lint || true

      - name: Run tests (if present)
        run: bun workspace run test || true

      - name: Build workspaces (optional)
        run: bun workspace run build || true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/backend
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/mansyar/carbon-mon-rep/backend:${{ github.sha }}
            ghcr.io/mansyar/carbon-mon-rep/backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/frontend
          file: ./packages/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/mansyar/carbon-mon-rep/frontend:${{ github.sha }}
            ghcr.io/mansyar/carbon-mon-rep/frontend:latest
